name: App build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install CocoaPods, build pods
        run: |
          sudo gem install cocoapods
          pod install
      - name: Build app
        run: |
          xcodebuild -list -workspace FreenetTray.xcworkspace
