name: App build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install CocoaPods, build pods
        run: |
          sudo gem install --no-document cocoapods
          pod install
      - name: Available schemes
        run: xcodebuild -list -workspace FreenetTray.xcworkspace
      - name: Test app
        run: xcodebuild -scheme FreenetTrayTests build
      - name: Build app
        run: xcodebuild -scheme FreenetTray build
